apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b0f9yucax-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b0f9yucax-python 
  name: b0f9yucax-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b0f9yucax-python 
